# Generated by Django 4.2.3 on 2023-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_alter_produto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
