# Generated by Django 4.2.3 on 2023-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_produto_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
